---
# tasks file for ansible-role-sanity

- name: fail if os family is not linux
  fail: 
    msg: Sanity supports on Linux OS host only
  when: ansible_os_family|lower != "redhat"

- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - url
  - username
  - password
  - is_reporter
  - is_selenium
  - is_safari

- name: sanity task
  include_tasks: "tasks/sanity.yml"