
# download the file

- name: download from s3 url
  get_url:
    url: "{{ s3_download_url }}/{{item}}"
    dest: "{{ installation_folder }}/{{ item }}"
    timeout: "{{ download_timeout | default(60) }}"
    owner: "{{ ansible_user_id }}"
    mode: '0777'
  when: custom_download_url == ""
  with_items:
  - "{{sanity_jar}}"
  - "{{android_app}}"
  - "{{ios_app}}"

- name: download from custom url
  get_url:
    url: "{{ custom_download_url }}/{{item}}"
    dest: "{{ installation_folder }}/{{item}}"
    timeout: "{{ download_timeout | default(60) }}"
    owner: "{{ ansible_user_id }}"
    mode: '0777'
  when: custom_download_url != ""
  with_items:
  - "{{sanity_jar}}"
  - "{{android_app}}"
  - "{{ios_app}}"

- name: print java full command
  debug: msg="export DISPLAY=:0 && java -jar {{ jar_file_path }} {{ url }} YourUsername YourPassword {{ chrome_driver_path }} {{ android_app_path }} {{ ios_app_path }} {{ is_reporter }} {{ is_selenium }} {{ is_safari }} {{ is_appium_oss }}"

- name: start jar
  shell: export DISPLAY=:0 && java -jar {{ jar_file_path }} {{ url }} {{ username }} {{ password }} {{ chrome_driver_path }} {{ android_app_path }} {{ ios_app_path }} {{ is_reporter }} {{ is_selenium }} {{ is_safari }} {{ is_appium_oss }}
  register: result
  become: no

# Print Status
- name: test results
  debug: msg="{{ result.stdout_lines }}"
